config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :employees
  resources :documents
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  #get  'home' => 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  DOC_TYPES = ['Personal ID','Marksheet','Photo ID','Address Proof','Others'].freeze
  
  belongs_to :employee
  validates :name, :doc_type, presence: true
  has_one_attached :image
end
 

app/models/employee.rb
class Employee < ApplicationRecord
   JOB_TITLE = ['CEO','CTO','HR Manager','Junior HR','CIO/Chief Digital Officer/Chief Innovation Officer','VP of Product Management/Head of Product','Product Manager','VP of Marketing','Software Architect','Technical Lead/Engineering Lead/Team Lead','Principal Software Engineer','Senior Software Engineer/Senior Software Developer
','Software Engineer','Software Developer','Junior Software Developer','Intern Software Developer'].freeze



   has_many :documents
   has_one_attached :profile_pick
	validates :first_name, :last_name, presence: true
	validates :personal_email, presence: true, uniqueness: true
	validates :city, :state, :country, :pincode, :address_line_1, presence: true
	validates :mobile_number ,:date_of_birth,:job_title , presence: true
   def name 
   	"#{first_name} #{last_name}".strip
   end	
   
   def full_address
   	"#{address_line_1}, #{city}, #{state},#{country},#{pincode}".strip
   end
   
   def name_with_email
      "#{name}(#{personal_email})"
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:edit, :update, :show, :destroy]
	def index
      @documents = Document.all
	end

	def new
	   @document = Document.new
	end
    
    def create
    	  @document = Document.new(document_params)
    	if @document.save
    	   redirect_to documents_path, notice: "Document has been created Successfully "
    	else
    	  render :new 
    	end	
    end 

    def edit
       # @document = Document.find(set_document)
    end
    def update
        #@document =Document.find(set_document)
        if @document.update(document_params)
            redirect_to documents_path, notice: "document has been update Successfully"
        else
          render 'edit'  
        end  
    end

    def show
       # @document = Document.find(set_document)
    end 

     def destroy
        #@document = Document.find(set_document)
        if @document.destroy
            redirect_to documents_path, notice: "document has been Delete Successfully"
        end
    end 

    private
    
    def document_params
    	params.require(:document).permit(:name, :doc_type, :employee_id, :image)
    end

    def set_document
    	@document = Document.find(params[:id])
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index
      @employees = Employee.all
	end

	def new
	   @employee = Employee.new
	end
    
    def create
    	@employee = Employee.new(employee_params)
    	if @employee.save
    		redirect_to employees_path, notice: "Employee has been created Successfully "
    	else
    	  render :new 
    	end	
    end 

    def edit
        @employee = Employee.find(params[:id])
    end
    def update
        @employee = Employee.find(params[:id])
        if @employee.update(employee_params)
            redirect_to employees_path, notice: "employee has been update Successfully"
        else
          render 'edit'  
        end  
    end

    def show
        @employee = Employee.find(params[:id])
    end 

     def destroy
        @employee = Employee.find(params[:id])
        if @employee.destroy
            redirect_to employees_path, notice: "employee has been Delete Successfully"
        end
    end 

    private
    
    def employee_params
    	params.require(:employee).permit(:first_name, :last_name,:personal_email, :address_line_1, :city,:state,:country,:pincode,:mobile_number,:date_of_birth,:job_title, :profile_pick)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form| %>
  <div class="row">
  	<div class="col-lg-4">
  	  <div class="form-group">
  	  	<%= form.label :name, class: 'mb-2'%>
  	  	<%= form.text_field :name, class: "form-control form-control-lg"%>
  	  	<% @document.errors.full_messages_for(:name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  	
  	  </div>
  	  <div class="form-group">
  	  	<%= form.label :document_type, class: 'mb-2'%>
        <%= form.select :doc_type, options_for_select(Document::DOC_TYPES, selected: document.doc_type ), {prompt: 'select document type'},{class: 'form-select form-select-lg'} %>
  	  	<% @document.errors.full_messages_for(:doc_type).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  	
  	  </div>
  	  <div class="form-group">
  	  	<%= form.label :employee_id, class: 'mb-2'%>
  	  <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name_with_email, employee.id]}, selected: document.doc_type ), {prompt: 'select employee '},{class: 'form-select form-select-lg'} %>
  	  	<% @document.errors.full_messages_for(:employee_id).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  	
  	  </div>
  	</div>
     <div class="form-group">
       <%=  form.label :image, class: 'mb-2' %><br>
       <%= form.file_field :image %>
     </div>
  </div>

  <div class="row">
		<div class="col-lg-12 mt-4">
			<%= form.submit class: "btn btn-primary btn-lg"%>
			<%= link_to "back to documents", documents_path, class: "btn btn-outline-primary btn-lg"%>
		</div>
	</div>
<% end %>

app/views/documents/edit.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Edit Document </h2>
		</div>
	</div>
	<%= render 'form', document: @document %>
</div>

app/views/documents/index.html.erb
<div class="col-lg-12">	
	<%= flash[:notice ] %>
	<div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Employees Document List </h2>
		</div>
	</div>
	<%= link_to "Create Document", new_document_path, class: "btn btn-primary btn-lg mb-4 " %>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th> Name</th>
				<th> Doc_type  </th>
				<th>Employee</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @documents.each do |document| %>
			<tr>
				<td><%= document.name %></td>
				<td><%= document.doc_type %></td>
				<td><%= link_to document.employee.name, employee_path(document.employee) %></td>
				<td>
					<%= link_to "Edit", edit_document_path(document), class: "btn btn-primary "%>
					<%= link_to "View", document_path(document), class: "btn btn-info "%>
					<%= link_to "Delete", document_path(document), method: :delete, data: { confirm:"Are You Soure Delete This Document " }, class: "btn btn-danger "%>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Create New Document </h2>
		</div>
	</div>
	<%= render 'form', document: @document %>
</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
		<div class="card-body">
			<h2 class="text-center">Document Deatils  Deatils  </h2>
			<div class="row">
				<div class="col-lg-6">
				<% if @document.image.attached? %>
				 <%= image_tag @document.image %>
				 
                <% end %>
				 <p class="lead"><strong> Name: - </strong><%= @document.name%></p>
	             <p class="lead"><strong> Doc_Type: - </strong><%= @document.doc_type %></p>
	              <p class="lead"><strong> Employee : - </strong><%= @document.employee.name  %></p>
				</div>
			</div>
			<%= link_to "Back To Document ", documents_path, class: "btn btn-outline-primary btn-lg"%>
			<%= link_to "Edit Employee", edit_document_path(@document), class: "btn btn-outline-danger btn-lg"%>
		</div>
	</div>
</div>

app/views/employees/_form.html.erb
<%= form_with model: employee  do |form| %>
  <div class="row">

	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :first_name, class: "mb-2"%>
	   	  	<%= form.text_field :first_name, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  
	   	  </div>
	   	</div>
        	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :Profile , class: "mb-2"%>
	   	  	<%= form.file_field :profile_pick, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:first_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  
	   	  </div>
	   	</div>

	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :last_name, class: "mb-2"%>
	   	  	<%= form.text_field :last_name, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:last_name).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  
	   	  </div>
	   	</div>
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :Job_title, class: "mb-2"%>
	   	  	<%= form.select :job_title, options_for_select(Employee::JOB_TITLE, selected: employee.job_title ),{prompt:'select Job type'},{class: 'form-select form-select-lg'} %>
	   	  	<% @employee.errors.full_messages_for(:job_title).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	  
	   	  </div>
	   	</div>
    </div>
    <div class="row">
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :email, class: "mb-2"%>
	   	  	<%= form.email_field :personal_email, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:personal_email).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	 
	   	  </div>
	   	</div>
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :date_of_birth, class: "mb-2"%>
	   	  	<%= form.date_field :date_of_birth, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:date_of_birth).each do |message| %>
           <p class="text-danger"><%= message %></p>
        <% end %>  	 
	   	  </div>
	   	</div>
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :Mobile, class: "mb-2"%>
	   	  	<%= form.text_field :mobile_number, class: "form-control form-control-lg" %>
	   	  	<% @employee.errors.full_messages_for(:mobile_number).each do |message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>  	 
	   	  </div>
	   	</div>
	</div>
	<div class="row">
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :address_line_1, class: "mb-2"%>
	   	  	<%= form.text_field :address_line_1, class: "form-control form-control-lg" %>
	   	  </div>
	   	</div>
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :city, class: "mb-2"%>
	   	  	<%= form.text_field :city, class: "form-control form-control-lg" %>
	   	  </div>
	   	</div>
	</div>
	<div class="row"> 
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :state, class: "mb-2"%>
	   	  	<%= form.text_field :state, class: "form-control form-control-lg" %>
	   	  </div>
	   	</div>
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :country, class: "mb-2"%>
	   	  	<%= form.country_select :country,{prompt:'select Country'},{class: 'form-select form-select-lg'} %>
	   	  </div>
	   	</div>
	</div>
	<div class="row"> 
	   	<div class="col-lg-4">
	   	  <div class="form-group">
	   	  	<%= form.label :pincode, class: "mb-2"%>
	   	  	<%= form.text_field :pincode, class: "form-control form-control-lg mb-4" %>
	   	  </div>
	   	</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<%= form.submit class: "btn btn-primary btn-lg"%>
			<%= link_to "back to employee", employees_path, class: "btn btn-outline-primary btn-lg"%>
		</div>
	</div>
<% end %>

app/views/employees/edit.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Create New Employee </h2>
		</div>
	</div>
	<%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">	
	<%= flash[:notice ] %>
	<div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Employees List</h2>
		</div>
	</div>
	<%= link_to "Create Employees", new_employee_path, class: "btn btn-primary btn-lg mb-4 " %>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th> Name</th>
				<th>Email </th>
				<th>Mobile </th>
				<th>Address</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @employees.each do |employee| %>
			<tr>
				<td><%= employee.name %></td>
				<td><%= employee.personal_email %></td>
				<td><%= employee.mobile_number %></td>
				<td><%= employee.full_address %></td>
				<td>
					<%= link_to "Edit", edit_employee_path(employee), class: "btn btn-primary "%>
					<%= link_to "View", employee_path(employee), class: "btn btn-info "%>
					<%= link_to "Delete", employee_path(employee), method: :delete, data: { confirm:"Are You Soure Delete This Employee" }, class: "btn btn-danger "%>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
  <div class="card mt-5 mb-5 ">
		<div class="card-body">
		  <h2 class="text-center"> Create New Employee </h2>
		</div>
	</div>
	<%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
		<div class="card-body">
			<h2 class="text-center">Employee Deatils  </h2>
			<div class="row">
				<div class="col-lg-6">
				 <h3 class="text-center"> Personal Information </h3>
				 <% if @employee.profile_pick.attached? %>
				 <%= image_tag @employee.profile_pick %>
                <% end %>	
				 <p class="lead"><strong>First Name: - </strong><%= @employee.first_name%></p>
				 <p class="lead"><strong>Last Name: - </strong><%= @employee.last_name%></p>
				  <p class="lead"><strong>Last Name: - </strong><%= @employee.personal_email %></p>
				   <p class="lead"><strong>Date Of Birth: - </strong><%= @employee.date_of_birth %></p>
				   <p class="lead"><strong>Job Title: - </strong><%= @employee.job_title %></p>
				</div>
				<div class="col-lg-6">
				 <h3 class="text-center"> Address Information  </h3>
				  <p class="lead"><strong>Address Line : - </strong><%= @employee.address_line_1%></p>
				 <p class="lead"><strong>City: - </strong><%= @employee.city %></p>
				  <p class="lead"><strong>State: - </strong><%= @employee.state %></p>
				   <p class="lead"><strong>Country: - </strong><%= @employee.country %></p>
				    <p class="lead"><strong>Pincode: - </strong><%= @employee.pincode %></p>		
				</div>
			</div>
			<div class="row mt-5">
				<h2 class="text-center" > Employee Documents </h2>
				<% @employee.documents.each do |document|%>
				 <div class="card">
				 	<div class="card-body" >
				 	  <div class="row">
				 	  	<% if document.image.attached? %>
				 	  	<div class="col-lg-4">
				 	  		<%= image_tag document.image, class: "img-fluid" %>
				 	  	</div>
				 	  	<% end %>
				 	  	<div class="col-lg-4">
				 	  		<p class="lead">Document Name: <%= document.name %></p>
				 	  	</div>
				 	  	<div class="col-lg-4">
				 	  		<p class="lead">Document Type:  <%= document.doc_type %></p>
				 	  	</div>
				 	  </div>
				 	</div>
				 </div>
				<% end %>
			</div>
			<%= link_to "Back To Employee", employees_path, class: "btn btn-outline-primary btn-lg"%>
			<%= link_to "Edit Employee", edit_employee_path(@employee), class: "btn btn-outline-danger btn-lg"%>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="col-lg-12">	
	
	<h1>Welcome To HR-Mitra </h1>
	<p class="lead"> Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32. </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <div class="container" >
      <div class="row">
         <%= yield %>
         <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class=" col-lg-10 mx-auto">
  <h1 class= "text-center mt-5 mb-4">About HR-Mitra</h1>
  <%= render 'shared/dummy_contant'%>
</div>
<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<div class=" col-lg-10 mx-auto">
  <h1 class= "text-center mt-5 mb-4">Contact HR-Mitra</h1>

  <!-- Wrapper container -->
<div class="container py-4">

  <!-- Bootstrap 5 starter form -->
  <form id="contactForm" data-sb-form-api-token="API_TOKEN">

    <!-- Name input -->
    <div class="mb-3">
      <label class="form-label" for="name">Name</label>
      <input class="form-control" id="name" type="text" placeholder="Name" data-sb-validations="required" />
      <div class="invalid-feedback" data-sb-feedback="name:required">Name is required.</div>
    </div>

    <!-- Email address input -->
    <div class="mb-3">
      <label class="form-label" for="emailAddress">Email Address</label>
      <input class="form-control" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required, email" />
      <div class="invalid-feedback" data-sb-feedback="emailAddress:required">Email Address is required.</div>
      <div class="invalid-feedback" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
    </div>

    <!-- Message input -->
    <div class="mb-3">
      <label class="form-label" for="message">Message</label>
      <textarea class="form-control" id="message" type="text" placeholder="Message" style="height: 10rem;" data-sb-validations="required"></textarea>
      <div class="invalid-feedback" data-sb-feedback="message:required">Message is required.</div>
    </div>

    <!-- Form submissions success message -->
    <div class="d-none" id="submitSuccessMessage">
      <div class="text-center mb-3">Form submission successful!</div>
    </div>

    <!-- Form submissions error message -->
    <div class="d-none" id="submitErrorMessage">
      <div class="text-center text-danger mb-3">Error sending message!</div>
    </div>

    <!-- Form submit button -->
    <div class="d-grid">
      <button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button>
    </div>

  </form>

</div>

<!-- SB Forms JS -->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</div>

<%= render 'shared/links' %>

app/views/shared/_dummy_contant.html.erb
<p class="lead">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
 </p>
 <p class="lead">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
 </p>
 <p class="lead">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
 </p>

app/views/shared/_footer.html.erb
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: #3f51b5">
    <!-- Grid container -->
    <div class="container">
      <!-- Section: Links -->
      <section class="mt-5">
        <!-- Grid row-->
        <div class="row text-center d-flex justify-content-center pt-5">
          <!-- Grid column -->
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <%= link_to "About Us ", about_path, target: '_/blank', class: "text-white" %>
            </h6>
          </div>
          <!-- Grid column -->


          <!-- Grid column -->
         
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
             <%= link_to " Home ", root_path, class: "text-white" %>
            </h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
               <%= link_to "Contact Us ", contact_path, target: '_/blank', class: "text-white" %>
            </h6>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-5" />

      <!-- Section: Text -->
      <section class="mb-5">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
              distinctio earum repellat quaerat voluptatibus placeat nam,
              commodi optio pariatur est quia magnam eum harum corrupti
              dicta, aliquam sequi voluptate quas.
            </p>
          </div>
        </div>
      </section>
      <!-- Section: Text -->

      <!-- Section: Social -->
      <section class="text-center mb-5">
        <a href="" class="text-white me-4">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="text-white me-4">
          <i class="fab fa-github"></i>
        </a>
      </section>
      <!-- Section: Social -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2022 Copyright:
      <a class="text-white" href="#"
         >HR-Mitra.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
<!-- End of .container

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <%= link_to "HR-Mitra", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
           <%= link_to "Employess",  employees_path, class:"navbar-brand" %>
        </li>
         <li class="nav-item">
              <%= link_to "Documents",  documents_path, class:"navbar-brand" %>

        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<div class="col-md-2">
<h6 class="text-uppercase font-weight-bold">
<%= link_to "About US ", about_path, target: '_/blank', class: "text-white" %>
</h6>
</div>

<div class="col-md-2">
<h6 class="text-uppercase font-weight-bold">
<%= link_to "Contact Us ", contact_path, target: '_/blank', class: "text-white" %>
</h6>
</div>